version: "3.8"

services:

  @docker.artifactId@:
    image: "@docker.image.name@:@project.version@"
    container_name: "@docker.artifactId@"
    environment:
      - "OPENEASE_ENV=${OPENEASE_ENV}"
    expose:
      # Elasticsearch embedded server port
      - 9200
    ports:
      # Elasticsearch embedded server port
      - "9200:9200"
      # Application port
      - "@service.port@:@service.port@"
    networks:
      openease:
        aliases:
          - "@docker.artifactId@"

networks:
  openease:
    name: "openease"
