# Spring Boot
management:
  endpoint:
    health:
      show-details: "never"
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "https://@service.name@.openease.com/security/auth/oauth2/callback/{registrationId}"
          apple:
            redirect-uri: "https://@service.name@.openease.com/security/auth/oauth2/callback/{registrationId}"

# Config
config:
  url: "https://@service.name@.openease.com"
  mask-5xx-errors: true
  filters:
    debug:
      enabled: false

# Managers
manager:
  event-log:
    enabled: true
  remoteEmail:
    api:
      baseUrl: "https://email.openease.com/v1/emails"
  remoteSms:
    api:
      baseUrl: "https://sms.openease.com/v1/sms"
  remotePayment:
    api:
      baseUrl: "https://payment.openease.com/v1/payments"
  captcha:
    enabled: true
