# Spring Boot
server:
  port: @service.port@
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    encoding:
      enabled: true
      charset: "UTF-8"
      force: true
management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "info"
          - "monitoring"
      cors:
        allowed-origin-patterns:
          - "https://openease.com:[*]"
          - "https://*.openease.com:[*]"
          - "http://local.openease.com:[*]"
          - "http://localhost:[*]"
        allowed-methods:
          - "HEAD"
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "PATCH"
          - "OPTIONS"
        allowed-headers:
          - "X-Requested-With"
          - "Content-Type"
          - "Accept"
          - "Origin"
        exposed-headers:
        allow-credentials: true
        max-age: 3600
  endpoint:
    health:
      show-details: "always"
spring:
  application:
    name: "@project.name@"
  profiles:
    active: "${@environment.systemProperty@}"
  thymeleaf:
    enabled: true
    cache: true
    mode: "TEXT"
    encoding: "UTF-8"
    servlet:
      content-type: "text/html"
    prefix: "/WEB-INF/thymeleaf/"
    suffix: ".html"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "..."
            client-secret: "..."
            redirect-uri: "{baseUrl}/sessions/oauth2/callback/{registrationId}"
            scope:
              - "openid"
              - "profile"
              - "email"
#          facebook:
#            client-id: "..."
#            client-secret: "..."
#            scope:
#              - "public_profile"
#              - "email"
#        provider:
#          facebook:
#            authorization-uri: "https://www.facebook.com/v3.0/dialog/oauth"
#            token-uri: "https://graph.facebook.com/v3.0/oauth/access_token"
#            user-info-uri: "https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture"

# JavaMelody
javamelody:
  enabled: true
  spring-monitoring-enabled: true
  management-endpoint-monitoring-enabled: true
  init-parameters:
    log: true
    authorized-users: "admin:@buildNumber@"
#    url-exclude-pattern: "(/.*\\.css|/.*\\.js|/.*\\.png|/.*\\.jpg|/.*\\.gif|/.*\\.svg)"

# Actuator: info
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
  env: "${@environment.systemProperty@}"

# Config
config:

  # General
  name: "@project.name@"
  description: "@project.description@"
  simple-name: "@project.name@"
  group-id: "@project.groupId@"
  artifact-id: "@project.artifactId@"
  version: "@project.version@"
  build-date-year: @date.current.year@
  encoding: "@project.build.sourceEncoding@"
  vendor:
    name: "@project.organization.name@"
    simple-name: "@project.organization.name@"
    url: "@project.organization.url@"
    logo-ascii-resource-path: "/com/openease/common/openease-logo-ascii.txt"

  # System Properties
  system-properties:
    environment-key: "@environment.systemProperty@"

  mask-5xx-errors: false
  filters:
    debug:
      enabled: true

  cors:
    allowed-origin-patterns:
      - "https://openease.com:[*]"
      - "https://*.openease.com:[*]"
      - "http://local.openease.com:[*]"
      - "http://localhost:[*]"
    allowed-methods:
      - "HEAD"
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "PATCH"
      - "OPTIONS"
    allowed-headers:
      - "*"
    exposed-headers:
    allow-credentials: true
    max-age-seconds: 3600

  auth:
    token-secret: "@buildNumber@@buildNumber@@buildNumber@"
    token-expiration-seconds: 864000
    oauth2:
      # After successfully authenticating with the OAuth 2.0 Provider, we will be
      # generating an auth token for the user and sending the token to the
      # redirect_uri mentioned by the client in the /oauth2/authorize request.
      # We are not using cookies because they will not work well in mobile clients.
      authorized-redirect-uris:
        - "http://localhost:3000/oauth2/redirect"
        - "myandroidapp:///oauth2/redirect"
        - "myiosapp:///oauth2/redirect"

# Message Source
message-source:
  # comma-separated list
  basenames: >
    classpath:/com/openease/service/www/lang/application-messages

# Task Executor
task-executor:
  core-pool-size: 50
  max-pool-size: 100
  queue-capacity: 1000

# Services
service:
  elasticsearch-embedded:
    version: "@elasticsearch.version@"
    home-directory: "./target/elasticsearch"
    cluster:
      name: "local-cluster"
    node:
      name: "local-node"
    network:
      host: "0.0.0.0"

# Managers
manager:
  event-log:
    enabled: true
  template:
    prefix: "/WEB-INF/thymeleaf/templates"
  captcha:
    api:
      key:
        public: "FILL-ME-IN"
        private: "FILL-ME-IN"
    rest-url: "https://www.google.com/recaptcha/api/siteverify"
  subscription:
    # plan names are derived from the i18n message resources
    # tier values must match: com.openease.common.data.model.account.Tier
    # cost values are set in cents (decimals are not allowed)
    plans:
      # Plan: Free
      - tier: "TIER0"
        cost:
          currency: "USD"
          per-month: 0
          per-year: 0
      # Plan: Basic
      - tier: "TIER1"
        cost:
          currency: "USD"
          per-month: 500
          per-year: 5000
      # Plan: Pro
      - tier: "TIER2"
        cost:
          currency: "USD"
          per-month: 1000
          per-year: 10000

# Dummy account
dummy-account:
  email: "jane.doe@example.com"
  first-name: "Jane"
  last-name: "Doe"
