# Spring Boot
management:
  endpoint:
    health:
      show-details: "never"

# Config
config:
  url: "https://@service.name@.openease.com"
  mask5xxErrors: true
  filters:
    debug:
      enabled: false

# Managers
manager:
  eventLog:
    enabled: true
  remoteEmail:
    api:
      baseUrl: "https://email.openease.com/v1/emails"
  remoteSms:
    api:
      baseUrl: "http://sms.openease.com/v1/sms"
  remotePayment:
    api:
      baseUrl: "https://payment.openease.com/v1/payments"
  captcha:
    enabled: true
